spring:
  application:
    name: auth-patient
  datasource:
    url: jdbc:postgresql://localhost:5432/hospitalMG
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        provider:
          twitter:
            authorization-uri: https://twitter.com/i/oauth2/authorize
            token-uri: https://api.twitter.com/2/oauth2/token
            user-info-uri: https://api.twitter.com/2/users/me
            user-name-attribute: id
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - openid
              - profile
              - email
          github:
            client-id: ${GITHUB_CLIENT_ID:}
            client-secret: ${GITHUB_CLIENT_SECRET:}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/github"
            scope:
              - read:user
              - user:email
          twitter:
            client-id: ${TWITTER_CLIENT_ID:}
            client-secret: ${TWITTER_CLIENT_SECRET:}
            provider: twitter
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/twitter
            scope:
              - tweet.read
              - users.read
              - offline.access
            client-name: Twitter

server:
  port: 8080
  servlet:
    context-path: /api/v1

jwt:
  secretKey: asdfhads9f67as98dfyaisudhfa98s67dfy89aishudfuays89dfyasi8df7asdf87987g98a7sg986a89sdf7ygit